#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Peritumoral Volume (PTV) generation from a tumor mask using 3D morphology.

This script is designed for the DeepComp nnU-Net module. It generates a
peritumoral ring from a pre-segmented tumor mask, using millimeter-based
3D Euclidean distance transforms so that anisotropic voxel spacing is handled
correctly.

Main analysis:
    1) Erode the tumor mask inward by 1 mm to reduce boundary partial-volume effects.
    2) Generate an outward peritumoral ring with a nominal thickness of 5 mm.
    3) Optionally generate sensitivity PTVs with 3 mm and 10 mm margins.
    4) Optionally exclude anatomically interfering regions, such as intraluminal gas,
       large vessels, and adjacent solid organs, if corresponding masks are available.

Important:
    This script does not train or run nnU-Net. It assumes that a tumor mask has
    already been generated by nnU-Net or manual annotation.
    This script also does not run VoxTell directly. If VoxTell-derived exclusion
    masks are available, pass them through --exclude-mask.

Example:
    python generate_peritumoral_roi.py \
        --tumor-mask tumor_mask.nii.gz \
        --output-dir ./ptv_outputs \
        --case-id case001 \
        --margins-mm 5 3 10 \
        --inner-erosion-mm 1

Example with CT image and exclusion masks:
    python generate_peritumoral_roi.py \
        --image ct_image.nii.gz \
        --tumor-mask tumor_mask.nii.gz \
        --exclude-mask voxtell_gas_vessels_organs_mask.nii.gz \
        --output-dir ./ptv_outputs \
        --case-id case001 \
        --margins-mm 5 3 10 \
        --inner-erosion-mm 1 \
        --exclude-gas-by-hu \
        --gas-threshold-hu -500

Outputs:
    case001_PTV_5mm.nii.gz
    case001_PTV_3mm.nii.gz
    case001_PTV_10mm.nii.gz
    case001_PTV_metrics.json

Labels in output masks:
    0 = background
    1 = peritumoral ROI
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import nibabel as nib
import numpy as np
from scipy import ndimage as ndi


def load_nifti(path: str | Path) -> Tuple[np.ndarray, nib.Nifti1Image]:
    """Load a NIfTI file and return data array and nibabel image object."""
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")
    img = nib.load(str(path))
    data = np.asanyarray(img.dataobj)
    return data, img


def save_mask_like(mask: np.ndarray, reference_img: nib.Nifti1Image, output_path: str | Path) -> None:
    """Save a binary mask using geometry copied from a reference NIfTI image."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    mask_u8 = mask.astype(np.uint8)
    out_img = nib.Nifti1Image(mask_u8, reference_img.affine, reference_img.header.copy())
    out_img.header.set_data_dtype(np.uint8)
    out_img.header["descrip"] = b"DeepComp peritumoral ROI"
    nib.save(out_img, str(output_path))


def get_spacing_xyz(img: nib.Nifti1Image) -> Tuple[float, float, float]:
    """
    Return voxel spacing in array-axis order.

    nibabel arrays are generally indexed as (X, Y, Z) for NIfTI data.
    The first three zoom values correspond to the first three data axes.
    """
    zooms = img.header.get_zooms()[:3]
    return tuple(float(z) for z in zooms)


def ensure_same_shape(reference: np.ndarray, other: np.ndarray, name: str) -> None:
    """Raise a readable error if an auxiliary mask/image shape does not match the tumor mask."""
    if reference.shape != other.shape:
        raise ValueError(
            f"Shape mismatch for {name}: expected {reference.shape}, got {other.shape}. "
            "Please resample all masks/images to the same grid before running this script."
        )


def clean_binary_mask(mask: np.ndarray, min_voxels: int = 10) -> np.ndarray:
    """Convert input to boolean and remove tiny connected components."""
    binary = np.asarray(mask) > 0
    if binary.sum() == 0:
        raise ValueError("Tumor mask is empty after binarization.")

    labeled, n = ndi.label(binary)
    if n == 0:
        raise ValueError("No connected component found in tumor mask.")

    sizes = ndi.sum(np.ones_like(labeled, dtype=np.float32), labeled, index=np.arange(1, n + 1))
    keep_labels = np.where(sizes >= min_voxels)[0] + 1
    cleaned = np.isin(labeled, keep_labels)

    if cleaned.sum() == 0:
        raise ValueError(
            f"Tumor mask is empty after removing components smaller than {min_voxels} voxels."
        )
    return cleaned


def erode_by_distance(mask: np.ndarray, spacing: Tuple[float, float, float], erosion_mm: float) -> np.ndarray:
    """
    Erode a binary mask by a physical distance in millimeters.

    The distance transform is computed inside the mask. Voxels with distance
    greater than the erosion radius are retained.
    """
    if erosion_mm <= 0:
        return mask.copy()

    inside_distance = ndi.distance_transform_edt(mask, sampling=spacing)
    eroded = inside_distance > erosion_mm

    # Fallback: for very small tumors, erosion may remove the whole mask.
    # In that case keep the original tumor mask and record this in QC metrics.
    if eroded.sum() == 0:
        return mask.copy()

    return eroded


def dilate_by_distance(mask: np.ndarray, spacing: Tuple[float, float, float], dilation_mm: float) -> np.ndarray:
    """
    Dilate a binary mask by a physical distance in millimeters.

    The distance transform is computed outside the mask. Voxels within the
    dilation radius are included.
    """
    if dilation_mm <= 0:
        return mask.copy()

    outside_distance = ndi.distance_transform_edt(~mask, sampling=spacing)
    dilated = outside_distance <= dilation_mm
    return dilated


def generate_peritumoral_ring(
    tumor_mask: np.ndarray,
    spacing: Tuple[float, float, float],
    margin_mm: float = 5.0,
    inner_erosion_mm: float = 1.0,
    method: str = "erode_then_dilate",
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Generate a peritumoral ring using distance-based 3D morphology.

    Parameters
    ----------
    tumor_mask:
        Binary tumor mask.
    spacing:
        Voxel spacing in mm, ordered according to array axes.
    margin_mm:
        Nominal peritumoral ring thickness in mm.
    inner_erosion_mm:
        Inward erosion distance in mm.
    method:
        - "erode_then_dilate": erode tumor by inner_erosion_mm, then dilate the eroded core
          by margin_mm, and define the ring as dilated_core minus eroded_core.
          This follows the written workflow directly.
        - "outside_only": define the ring as voxels outside the original tumor and within
          margin_mm of the tumor surface. The eroded core is still computed for QC.

    Returns
    -------
    ring:
        Binary peritumoral ring.
    eroded_core:
        Tumor mask after inward erosion.
    expanded:
        Expanded mask used to construct the ring.
    """
    eroded_core = erode_by_distance(tumor_mask, spacing, inner_erosion_mm)

    if method == "erode_then_dilate":
        expanded = dilate_by_distance(eroded_core, spacing, margin_mm)
        ring = expanded & (~eroded_core)
    elif method == "outside_only":
        expanded = dilate_by_distance(tumor_mask, spacing, margin_mm)
        ring = expanded & (~tumor_mask)
    else:
        raise ValueError("method must be either 'erode_then_dilate' or 'outside_only'.")

    return ring, eroded_core, expanded


def build_exclusion_mask(
    tumor_shape: Tuple[int, int, int],
    image_path: Optional[str | Path] = None,
    exclude_mask_paths: Optional[Iterable[str | Path]] = None,
    exclude_gas_by_hu: bool = False,
    gas_threshold_hu: float = -500.0,
) -> np.ndarray:
    """
    Build a combined exclusion mask.

    Exclusion sources:
    1. VoxTell-derived or manually prepared masks passed through --exclude-mask.
       Nonzero voxels are excluded.
    2. Optional gas exclusion from CT intensity threshold if --image is provided.
       Voxels <= gas_threshold_hu are excluded.
    """
    exclusion = np.zeros(tumor_shape, dtype=bool)

    if exclude_mask_paths:
        for p in exclude_mask_paths:
            data, _ = load_nifti(p)
            ensure_same_shape(np.zeros(tumor_shape, dtype=np.uint8), data, f"exclude mask {p}")
            exclusion |= (data > 0)

    if exclude_gas_by_hu:
        if image_path is None:
            raise ValueError("--exclude-gas-by-hu requires --image.")
        img_data, _ = load_nifti(image_path)
        ensure_same_shape(np.zeros(tumor_shape, dtype=np.uint8), img_data, "image")
        exclusion |= (img_data <= gas_threshold_hu)

    return exclusion


def volume_cm3(mask: np.ndarray, spacing: Tuple[float, float, float]) -> float:
    """Compute mask volume in cm^3."""
    voxel_volume_mm3 = float(np.prod(spacing))
    return float(mask.sum()) * voxel_volume_mm3 / 1000.0


def mask_voxel_count(mask: np.ndarray) -> int:
    """Return number of nonzero voxels as Python int."""
    return int(np.asarray(mask).sum())


def run_ptv_generation(
    tumor_mask_path: str | Path,
    output_dir: str | Path,
    case_id: Optional[str] = None,
    image_path: Optional[str | Path] = None,
    exclude_mask_paths: Optional[List[str | Path]] = None,
    margins_mm: Optional[List[float]] = None,
    inner_erosion_mm: float = 1.0,
    method: str = "erode_then_dilate",
    exclude_gas_by_hu: bool = False,
    gas_threshold_hu: float = -500.0,
    min_tumor_component_voxels: int = 10,
) -> Dict[str, object]:
    """Main execution function for PTV generation."""
    tumor_data, tumor_img = load_nifti(tumor_mask_path)
    spacing = get_spacing_xyz(tumor_img)

    tumor_mask = clean_binary_mask(tumor_data, min_voxels=min_tumor_component_voxels)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if case_id is None:
        name = Path(tumor_mask_path).name
        case_id = name.replace(".nii.gz", "").replace(".nii", "").replace("_mask", "")

    if margins_mm is None:
        margins_mm = [5.0, 3.0, 10.0]

    exclusion = build_exclusion_mask(
        tumor_shape=tumor_mask.shape,
        image_path=image_path,
        exclude_mask_paths=exclude_mask_paths,
        exclude_gas_by_hu=exclude_gas_by_hu,
        gas_threshold_hu=gas_threshold_hu,
    )

    metrics: Dict[str, object] = {
        "case_id": case_id,
        "tumor_mask_path": str(tumor_mask_path),
        "image_path": str(image_path) if image_path else None,
        "exclude_mask_paths": [str(p) for p in exclude_mask_paths] if exclude_mask_paths else [],
        "spacing_mm": spacing,
        "inner_erosion_mm": inner_erosion_mm,
        "method": method,
        "exclude_gas_by_hu": exclude_gas_by_hu,
        "gas_threshold_hu": gas_threshold_hu if exclude_gas_by_hu else None,
        "tumor_voxels": mask_voxel_count(tumor_mask),
        "tumor_volume_cm3": round(volume_cm3(tumor_mask, spacing), 4),
        "exclusion_voxels": mask_voxel_count(exclusion),
        "ptv": {},
        "notes": [],
    }

    for margin in margins_mm:
        ring, eroded_core, expanded = generate_peritumoral_ring(
            tumor_mask=tumor_mask,
            spacing=spacing,
            margin_mm=float(margin),
            inner_erosion_mm=float(inner_erosion_mm),
            method=method,
        )

        ring_before_exclusion = ring.copy()
        ring = ring & (~exclusion)

        margin_label = f"{margin:g}mm"
        out_path = output_dir / f"{case_id}_PTV_{margin_label}.nii.gz"
        save_mask_like(ring, tumor_img, out_path)

        metrics["ptv"][margin_label] = {
            "output_path": str(out_path),
            "margin_mm": float(margin),
            "eroded_core_voxels": mask_voxel_count(eroded_core),
            "expanded_voxels": mask_voxel_count(expanded),
            "ptv_voxels_before_exclusion": mask_voxel_count(ring_before_exclusion),
            "ptv_voxels_after_exclusion": mask_voxel_count(ring),
            "excluded_from_ptv_voxels": mask_voxel_count(ring_before_exclusion & exclusion),
            "ptv_volume_cm3": round(volume_cm3(ring, spacing), 4),
        }

        if ring.sum() == 0:
            metrics["notes"].append(
                f"PTV {margin_label} is empty after exclusion. Check tumor mask, margin, or exclusion masks."
            )

    metrics_path = output_dir / f"{case_id}_PTV_metrics.json"
    with open(metrics_path, "w", encoding="utf-8") as f:
        json.dump(metrics, f, indent=2, ensure_ascii=False)

    metrics["metrics_path"] = str(metrics_path)
    return metrics


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate peritumoral volumes from a tumor mask using 3D morphology."
    )
    parser.add_argument(
        "--tumor-mask",
        required=True,
        help="Path to binary or label tumor mask NIfTI file. Nonzero voxels are treated as tumor.",
    )
    parser.add_argument(
        "--image",
        default=None,
        help="Optional CT image NIfTI path. Required only when using --exclude-gas-by-hu.",
    )
    parser.add_argument(
        "--exclude-mask",
        nargs="*",
        default=None,
        help=(
            "Optional exclusion mask paths, for example VoxTell-derived masks of gas, "
            "large vessels, liver, pancreas, spleen, or other interfering structures. "
            "All nonzero voxels are excluded from the PTV."
        ),
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Directory to save PTV masks and metrics JSON.",
    )
    parser.add_argument(
        "--case-id",
        default=None,
        help="Case ID used as output filename prefix. Defaults to tumor mask filename.",
    )
    parser.add_argument(
        "--margins-mm",
        nargs="+",
        type=float,
        default=[5.0, 3.0, 10.0],
        help="Peritumoral margins in mm. Default: 5 3 10.",
    )
    parser.add_argument(
        "--inner-erosion-mm",
        type=float,
        default=1.0,
        help="Inward tumor erosion distance in mm. Default: 1.",
    )
    parser.add_argument(
        "--method",
        choices=["erode_then_dilate", "outside_only"],
        default="erode_then_dilate",
        help=(
            "PTV construction method. 'erode_then_dilate' follows the written workflow. "
            "'outside_only' creates only the external ring outside the original tumor."
        ),
    )
    parser.add_argument(
        "--exclude-gas-by-hu",
        action="store_true",
        help="Exclude gas-like voxels from the CT image using HU threshold.",
    )
    parser.add_argument(
        "--gas-threshold-hu",
        type=float,
        default=-500.0,
        help="HU threshold for gas exclusion. Voxels <= this value are excluded. Default: -500.",
    )
    parser.add_argument(
        "--min-tumor-component-voxels",
        type=int,
        default=10,
        help="Remove tumor mask connected components smaller than this voxel count. Default: 10.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    metrics = run_ptv_generation(
        tumor_mask_path=args.tumor_mask,
        output_dir=args.output_dir,
        case_id=args.case_id,
        image_path=args.image,
        exclude_mask_paths=args.exclude_mask,
        margins_mm=args.margins_mm,
        inner_erosion_mm=args.inner_erosion_mm,
        method=args.method,
        exclude_gas_by_hu=args.exclude_gas_by_hu,
        gas_threshold_hu=args.gas_threshold_hu,
        min_tumor_component_voxels=args.min_tumor_component_voxels,
    )
    print(json.dumps(metrics, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
